
FROM cgr.dev/chainguard/node:latest AS build-dist
WORKDIR /usr/src/app
COPY --chown=node:node boilerplate ./
RUN npm install 
RUN npm run build 

FROM cgr.dev/chainguard/node:latest AS build-deps
ENV NODE_ENV=production
WORKDIR /usr/src/app
COPY --chown=node:node node-files/package.json node-files/package-lock.json ./
RUN npm ci --omit=dev

FROM cgr.dev/chainguard/node:latest
ENV nextBuildPath="./shared"
ENV NODE_ENV="production"
ENV PORT=3000
WORKDIR /app
COPY --chown=node:node --from=build-dist /usr/src/app/.next ./shared/.next
COPY --chown=node:node --from=build-dist /usr/src/app/public ./shared/public
COPY --chown=node:node --from=build-deps /usr/src/app ./
COPY --chown=node:node node-files ./

RUN chmod -R 755 ./shared/.next

EXPOSE 3000
ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["node","next-server.js"]  

# Size: 696mb
